package dev.michaellamb.tutorial.tour

import io.ktor.server.response.respond
import io.ktor.server.routing.Route
import io.ktor.server.routing.get

// Kotlin: data class.
// The compiler auto-derives equals(), hashCode(), toString(), copy(), and componentN()
// from the primary-constructor properties. `copy()` is the idiomatic way to make a
// modified copy of an immutable value.
data class User(val id: Int, val name: String, val email: String)

fun Route.dataClassRoutes() {
    get("/data-class") {
        val original = User(id = 1, name = "Han Solo", email = "han@falcon.test")
        val renamed = original.copy(name = "Chewbacca")

        // Destructuring uses componentN() generated by `data class`.
        val (_, name, email) = renamed

        call.respond(
            mapOf(
                "original" to original,
                "renamed_via_copy" to renamed,
                "destructured" to mapOf("name" to name, "email" to email),
                "equals_self" to (original == original.copy()),
                "to_string" to original.toString(),
            )
        )
    }
}
